/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.CargosDAO;
import DAO.FuncionarioDAO;
import classes.Cargo;
import classes.Funcionario;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author izael
 */
public class Interface extends javax.swing.JFrame {
    
    private String siglaExc;
    /**
     * Creates new form JFrameInicial
     */
    public Interface() {
        initComponents();
        listarCargos();
        listarFuncionarios();
        setCBoxCargos();
    }
    
    public void setCBoxCargos(){
        jCbCargo.removeAllItems();
        jCbAltCargo.removeAllItems();
        CargosDAO cgDAO = new CargosDAO();
        List<Cargo> cargos = cgDAO.listarNmCargos();
        int i = 0;
        while(cargos.size() > i){
            jCbCargo.addItem(String.valueOf(cargos.get(i).getNmCargo()));
            jCbAltCargo.addItem(String.valueOf(cargos.get(i).getNmCargo()));
            i++;
        }
    }
    
    public void listarFuncionarios(){
        DefaultTableModel valor = (DefaultTableModel) jTableFuncionarios.getModel();
        valor.getDataVector().removeAllElements();
        FuncionarioDAO fcDAO = new FuncionarioDAO();
        List<Funcionario> fc = fcDAO.listarFuncionarios();
        int i = 0;
        while(fc.size() > i){
            valor.addRow(new Object[]{String.valueOf(fc.get(i).getId()), fc.get(i).getNome(), fc.get(i).getRg(),
                fc.get(i).getCpf(), fc.get(i).getNmCargo()});
            i++;
        }
    }
    
    public void listarCargos(){
        DefaultTableModel valor = (DefaultTableModel) jTableCargos.getModel();
        
        valor.getDataVector().removeAllElements();
        CargosDAO cgDAO = new CargosDAO();
        
        List<Cargo> cargos = cgDAO.listarCargos();
        int i = 0;
        while (cargos.size() > i){
        
            valor.addRow(new Object[]{cargos.get(i).getSigla(), cargos.get(i).getNmCargo(), 
                String.valueOf(cargos.get(i).getSalario()), cargos.get(i).getDescricao()});
            i++;
            
        }
    }
    
    public boolean validaCamposCadCargo(){
        boolean notNull = true;
        if(jTxtSigla.getText().equals("")){
            notNull = false;
        } else if(jTxtCargo.getText().equals("")){
            notNull = false;
        } else if(jTxtDescricao.getText().equals("")){
            notNull = false;
        }
        return notNull;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelTopBar = new javax.swing.JPanel();
        jLbExit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelLeft = new javax.swing.JPanel();
        jBtFuncionarios = new javax.swing.JPanel();
        jLbIconFunc = new javax.swing.JLabel();
        jLbGFunc = new javax.swing.JLabel();
        jBtCargos = new javax.swing.JPanel();
        jLbIconCargos = new javax.swing.JLabel();
        jLbCargos = new javax.swing.JLabel();
        jPanelRight = new javax.swing.JPanel();
        jPanelFuncionarios = new javax.swing.JPanel();
        jLbGFunc1 = new javax.swing.JLabel();
        jTxtRg = new javax.swing.JTextField();
        jTxtNome = new javax.swing.JTextField();
        jFormTxtCpf = new javax.swing.JFormattedTextField();
        jCbCargo = new javax.swing.JComboBox<>();
        jLbGFunc6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFuncionarios = new javax.swing.JTable();
        jTxtAltRg = new javax.swing.JTextField();
        jTxtAltId = new javax.swing.JTextField();
        jTxtAltNome = new javax.swing.JTextField();
        jFormTxtAltCpf = new javax.swing.JFormattedTextField();
        jCbAltCargo = new javax.swing.JComboBox<>();
        jBtCadastrar = new javax.swing.JButton();
        jBtExcluir = new javax.swing.JButton();
        jBtAlterar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanelCargos = new javax.swing.JPanel();
        JLbCg = new javax.swing.JLabel();
        jLbCg2 = new javax.swing.JLabel();
        jLbCg3 = new javax.swing.JLabel();
        jLbCg4 = new javax.swing.JLabel();
        jLbCg5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtAltDescricao = new javax.swing.JTextArea();
        jTxtSigla = new javax.swing.JTextField();
        jTxtSalario = new javax.swing.JTextField();
        jLbCg6 = new javax.swing.JLabel();
        jTxtCargo = new javax.swing.JTextField();
        JLbCg1 = new javax.swing.JLabel();
        jBtExcCargo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCargos = new javax.swing.JTable();
        jLbCg7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTxtDescricao = new javax.swing.JTextArea();
        jLbCg8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtAltSalario = new javax.swing.JTextField();
        jBtCadCargo = new javax.swing.JButton();
        jBtAltCargo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTopBar.setBackground(new java.awt.Color(102, 0, 0));
        jPanelTopBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelTopBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbExit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLbExit.setForeground(new java.awt.Color(255, 255, 255));
        jLbExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbExit.setText("X");
        jLbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbExitMouseExited(evt);
            }
        });
        jPanelTopBar.add(jLbExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 30, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gerenciamento de Funcionários");
        jPanelTopBar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        getContentPane().add(jPanelTopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 30));

        jPanelLeft.setBackground(new java.awt.Color(51, 51, 51));
        jPanelLeft.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelLeft.setForeground(new java.awt.Color(51, 51, 51));
        jPanelLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtFuncionarios.setBackground(new java.awt.Color(51, 51, 51));
        jBtFuncionarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbIconFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/funcionario.png"))); // NOI18N
        jBtFuncionarios.add(jLbIconFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 60));

        jLbGFunc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbGFunc.setForeground(new java.awt.Color(255, 255, 255));
        jLbGFunc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbGFunc.setText("         Funcionários");
        jLbGFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbGFuncMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbGFuncMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbGFuncMouseExited(evt);
            }
        });
        jBtFuncionarios.add(jLbGFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 60));

        jPanelLeft.add(jBtFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 180, 60));

        jBtCargos.setBackground(new java.awt.Color(51, 51, 51));
        jBtCargos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbIconCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cargo.png"))); // NOI18N
        jBtCargos.add(jLbIconCargos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 60));

        jLbCargos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbCargos.setForeground(new java.awt.Color(255, 255, 255));
        jLbCargos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbCargos.setText("      Cargos");
        jLbCargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbCargosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbCargosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbCargosMouseExited(evt);
            }
        });
        jBtCargos.add(jLbCargos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 60));

        jPanelLeft.add(jBtCargos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 180, 60));

        getContentPane().add(jPanelLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 500));

        jPanelRight.setBackground(new java.awt.Color(230, 230, 230));
        jPanelRight.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelRight.setLayout(new java.awt.CardLayout());

        jPanelFuncionarios.setBackground(new java.awt.Color(230, 230, 230));
        jPanelFuncionarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbGFunc1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLbGFunc1.setForeground(new java.awt.Color(51, 51, 51));
        jLbGFunc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbGFunc1.setText("Editar/Excluir Funcionário:");
        jLbGFunc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbGFunc1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbGFunc1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbGFunc1MouseExited(evt);
            }
        });
        jPanelFuncionarios.add(jLbGFunc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 280, 30));

        jTxtRg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanelFuncionarios.add(jTxtRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 210, -1));

        jTxtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanelFuncionarios.add(jTxtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 210, -1));

        try {
            jFormTxtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormTxtCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanelFuncionarios.add(jFormTxtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 210, -1));

        jCbCargo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelFuncionarios.add(jCbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 210, -1));

        jLbGFunc6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLbGFunc6.setForeground(new java.awt.Color(51, 51, 51));
        jLbGFunc6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbGFunc6.setText("Cadastro de Funcionário");
        jLbGFunc6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbGFunc6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbGFunc6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbGFunc6MouseExited(evt);
            }
        });
        jPanelFuncionarios.add(jLbGFunc6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 250, 30));

        jTableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "RG", "CPF", "Cargo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFuncionarios);

        jPanelFuncionarios.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 620, 170));

        jTxtAltRg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtAltRg.setEnabled(false);
        jTxtAltRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAltRgActionPerformed(evt);
            }
        });
        jPanelFuncionarios.add(jTxtAltRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 210, -1));

        jTxtAltId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtAltId.setEnabled(false);
        jPanelFuncionarios.add(jTxtAltId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 100, -1));

        jTxtAltNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtAltNome.setEnabled(false);
        jPanelFuncionarios.add(jTxtAltNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 210, -1));

        jFormTxtAltCpf.setEnabled(false);
        jFormTxtAltCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanelFuncionarios.add(jFormTxtAltCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 200, -1));

        jCbAltCargo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCbAltCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCbAltCargo.setEnabled(false);
        jPanelFuncionarios.add(jCbAltCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 200, -1));

        jBtCadastrar.setBackground(new java.awt.Color(153, 0, 0));
        jBtCadastrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jBtCadastrar.setText("Cadastrar");
        jBtCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCadastrarActionPerformed(evt);
            }
        });
        jPanelFuncionarios.add(jBtCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 110, 30));

        jBtExcluir.setBackground(new java.awt.Color(153, 0, 0));
        jBtExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jBtExcluir.setText("Excluir");
        jBtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtExcluirActionPerformed(evt);
            }
        });
        jPanelFuncionarios.add(jBtExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 90, -1));

        jBtAlterar.setBackground(new java.awt.Color(153, 0, 0));
        jBtAlterar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jBtAlterar.setText("Alterar");
        jBtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAlterarActionPerformed(evt);
            }
        });
        jPanelFuncionarios.add(jBtAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 90, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Cargo:");
        jPanelFuncionarios.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Nome:");
        jPanelFuncionarios.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("RG:");
        jPanelFuncionarios.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("CPF:");
        jPanelFuncionarios.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Cargo:");
        jPanelFuncionarios.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Nome:");
        jPanelFuncionarios.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("RG:");
        jPanelFuncionarios.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("ID:");
        jPanelFuncionarios.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("CPF:");
        jPanelFuncionarios.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, -1));

        jPanelRight.add(jPanelFuncionarios, "TelaFuncionario");

        jPanelCargos.setBackground(new java.awt.Color(230, 230, 230));
        jPanelCargos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLbCg.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        JLbCg.setText("Editar/Excluir Cargo");
        jPanelCargos.add(JLbCg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLbCg2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLbCg2.setText("R$");
        jPanelCargos.add(jLbCg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLbCg3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbCg3.setText("Cargo:");
        jPanelCargos.add(jLbCg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLbCg4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbCg4.setText("Salário:");
        jPanelCargos.add(jLbCg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLbCg5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbCg5.setText("Sigla:");
        jPanelCargos.add(jLbCg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jTxtAltDescricao.setColumns(20);
        jTxtAltDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtAltDescricao.setRows(5);
        jTxtAltDescricao.setEnabled(false);
        jScrollPane2.setViewportView(jTxtAltDescricao);

        jPanelCargos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 260, 70));

        jTxtSigla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanelCargos.add(jTxtSigla, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 170, -1));

        jTxtSalario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanelCargos.add(jTxtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 140, -1));

        jLbCg6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbCg6.setText("Salário:");
        jPanelCargos.add(jLbCg6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jTxtCargo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanelCargos.add(jTxtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 170, -1));

        JLbCg1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        JLbCg1.setText("Cadastro de Cargo");
        jPanelCargos.add(JLbCg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jBtExcCargo.setBackground(new java.awt.Color(153, 0, 0));
        jBtExcCargo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtExcCargo.setForeground(new java.awt.Color(255, 255, 255));
        jBtExcCargo.setText("Excluir");
        jBtExcCargo.setEnabled(false);
        jBtExcCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtExcCargoActionPerformed(evt);
            }
        });
        jPanelCargos.add(jBtExcCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        jLabel2.setText("* Para centavos, colocar '.'");
        jPanelCargos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        jTableCargos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sigla", "Cargo", "Salario", "Descricao"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCargosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableCargos);

        jPanelCargos.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 620, 140));

        jLbCg7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbCg7.setText("Descrição:");
        jPanelCargos.add(jLbCg7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        jTxtDescricao.setColumns(20);
        jTxtDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtDescricao.setRows(5);
        jScrollPane4.setViewportView(jTxtDescricao);

        jPanelCargos.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 260, 70));

        jLbCg8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbCg8.setText("Descrição:");
        jPanelCargos.add(jLbCg8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("R$");
        jPanelCargos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        jTxtAltSalario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtAltSalario.setEnabled(false);
        jPanelCargos.add(jTxtAltSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 170, -1));

        jBtCadCargo.setBackground(new java.awt.Color(153, 0, 0));
        jBtCadCargo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtCadCargo.setForeground(new java.awt.Color(255, 255, 255));
        jBtCadCargo.setText("Cadastrar");
        jBtCadCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCadCargoActionPerformed(evt);
            }
        });
        jPanelCargos.add(jBtCadCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));

        jBtAltCargo.setBackground(new java.awt.Color(153, 0, 0));
        jBtAltCargo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtAltCargo.setForeground(new java.awt.Color(255, 255, 255));
        jBtAltCargo.setText("Alterar");
        jBtAltCargo.setEnabled(false);
        jBtAltCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAltCargoActionPerformed(evt);
            }
        });
        jPanelCargos.add(jBtAltCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel4.setText("* Só é possível alterar a descrição e o salário, caso contrário, apenas exclusão.");
        jPanelCargos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jPanelRight.add(jPanelCargos, "TelaCargos");

        getContentPane().add(jPanelRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 690, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLbCargosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbCargosMouseEntered
        this.setCursor(Cursor.HAND_CURSOR);
        jBtCargos.setBackground(new Color(83,83,83));
    }//GEN-LAST:event_jLbCargosMouseEntered

    private void jLbCargosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbCargosMouseExited
        this.setCursor(Cursor.DEFAULT_CURSOR);
        jBtCargos.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jLbCargosMouseExited

    private void jLbCargosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbCargosMouseClicked
        CardLayout cl = (CardLayout) jPanelRight.getLayout();
        cl.show(jPanelRight, "TelaCargos");
    }//GEN-LAST:event_jLbCargosMouseClicked

    private void jLbGFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFuncMouseClicked
        CardLayout cl = (CardLayout) jPanelRight.getLayout();
        cl.show(jPanelRight, "TelaFuncionario");
    }//GEN-LAST:event_jLbGFuncMouseClicked

    private void jLbGFuncMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFuncMouseEntered
        this.setCursor(Cursor.HAND_CURSOR);
        jBtFuncionarios.setBackground(new Color(83,83,83));
    }//GEN-LAST:event_jLbGFuncMouseEntered

    private void jLbGFuncMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFuncMouseExited
        this.setCursor(Cursor.DEFAULT_CURSOR);
        jBtFuncionarios.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jLbGFuncMouseExited

    private void jLbExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbExitMouseEntered
        this.setCursor(Cursor.HAND_CURSOR);
        jLbExit.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_jLbExitMouseEntered

    private void jLbExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbExitMouseExited
        this.setCursor(Cursor.DEFAULT_CURSOR);
        jLbExit.setForeground(new Color(240,240,240));
    }//GEN-LAST:event_jLbExitMouseExited

    private void jLbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLbExitMouseClicked

    private void jLbGFunc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc1MouseClicked

    private void jLbGFunc1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc1MouseEntered

    private void jLbGFunc1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc1MouseExited

    private void jLbGFunc6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc6MouseClicked

    private void jLbGFunc6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc6MouseEntered

    private void jLbGFunc6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc6MouseExited

    private void jTxtAltRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAltRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAltRgActionPerformed

    private void jBtCadCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCadCargoActionPerformed
        Cargo cg = new Cargo();
        CargosDAO cgDAO = new CargosDAO();
        if(jTxtSalario.getText().equals("") || Integer.parseInt(jTxtSalario.getText()) < 0){
            JOptionPane.showMessageDialog(null, "Defina um valor válido no campo SALÁRIO");
        }else{
            cg.setSigla(jTxtSigla.getText());
            cg.setNmCargo(jTxtCargo.getText());
            cg.setSalario(new BigDecimal(jTxtSalario.getText()));
            cg.setDescricao(jTxtDescricao.getText());
            if(validaCamposCadCargo() == true){
                try {
                    cgDAO.cadastrarCargo(cg);
                    JOptionPane.showMessageDialog(null,"Cargo "+cg.getNmCargo()+" cadastrado com sucesso.");
                } catch (SQLException ex) {
                    //Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
                    System.out.println(ex);
                }
                listarCargos();
                setCBoxCargos();
                jTxtSigla.setText("");
                jTxtCargo.setText("");
                jTxtSalario.setText("");
                jTxtDescricao.setText("");
            } else{
                JOptionPane.showMessageDialog(null, "Preencha todos os campos para prosseguir");
            } 
        }
        
    }//GEN-LAST:event_jBtCadCargoActionPerformed

    private void jBtAltCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAltCargoActionPerformed
        Cargo cg = new Cargo();
        cg.setSalario(new BigDecimal(jTxtAltSalario.getText()));
        cg.setDescricao(jTxtAltDescricao.getText());
        CargosDAO cgDAO = new CargosDAO();
        cgDAO.alterarCargo(cg);
        JOptionPane.showMessageDialog(null,"Cargo de sigla "+siglaExc+" alterado com sucesso.");
        listarCargos();
        jTxtAltSalario.setText("");
        jTxtAltSalario.setEnabled(false);
        jTxtAltDescricao.setText("");
        jTxtAltDescricao.setEnabled(false);
        jBtAltCargo.setEnabled(false);
        jBtExcCargo.setEnabled(false);
    }//GEN-LAST:event_jBtAltCargoActionPerformed

    private void jBtExcCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtExcCargoActionPerformed
        if(siglaExc != ""){
            Cargo cg = new Cargo();
            cg.setSigla(siglaExc);
            CargosDAO cgDAO = new CargosDAO();
            cgDAO.excluirCargo(cg);
            JOptionPane.showMessageDialog(null, "Cargo de sigla "+siglaExc+" excluído com sucesso");
            listarCargos();
            this.siglaExc = "";
        } else{
            JOptionPane.showMessageDialog(null, "Selecione um cargo para excluir");
        }
        listarCargos();
        setCBoxCargos();
        jTxtAltSalario.setText("");
        jTxtAltSalario.setEnabled(false);
        jTxtAltDescricao.setText("");
        jTxtAltDescricao.setEnabled(false);
        jBtAltCargo.setEnabled(false);
        jBtExcCargo.setEnabled(false);
    }//GEN-LAST:event_jBtExcCargoActionPerformed

    private void jTableCargosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCargosMouseClicked
        this.siglaExc = (String) jTableCargos.getModel().getValueAt(jTableCargos.getSelectedRow(), 0);
        jTxtAltSalario.setText((String) jTableCargos.getModel().getValueAt(jTableCargos.getSelectedRow(), 2));
        jTxtAltDescricao.setText((String) jTableCargos.getModel().getValueAt(jTableCargos.getSelectedRow(), 3));
        jTxtAltSalario.setEnabled(true);
        jTxtAltDescricao.setEnabled(true);
        jBtAltCargo.setEnabled(true);
        jBtExcCargo.setEnabled(true);
    }//GEN-LAST:event_jTableCargosMouseClicked

    private void jBtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCadastrarActionPerformed
        Funcionario fc = new Funcionario();
        fc.setNome(jTxtNome.getText());
        fc.setRg(jTxtRg.getText());
        fc.setCpf(jFormTxtCpf.getText());
        
        CargosDAO cgDAO = new CargosDAO();
        Cargo cg = new Cargo();
        cg.setSigla(cgDAO.descCgForNm((String)jCbCargo.getSelectedItem()));
        
        FuncionarioDAO fcDAO = new FuncionarioDAO();
        fcDAO.cadastroFunc(fc, cg);
        
        JOptionPane.showMessageDialog(null, "Funcionário "+fc.getNome()+" cadastrado com sucesso!");
        listarFuncionarios();
        
        jTxtNome.setText("");
        jTxtRg.setText("");
        jFormTxtCpf.setText("");
        int i = 0;
        jCbCargo.setSelectedItem(jCbCargo.getItemAt(i));
        
    }//GEN-LAST:event_jBtCadastrarActionPerformed

    private void jBtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAlterarActionPerformed
        Funcionario fc = new Funcionario();
        fc.setId(Integer.parseInt(jTxtAltId.getText()));
        fc.setNome(jTxtAltNome.getText());
        fc.setRg(jTxtAltRg.getText());
        fc.setCpf(jFormTxtAltCpf.getText());
        
        CargosDAO cgDAO = new CargosDAO();
        Cargo cg = new Cargo();
        cg.setSigla(cgDAO.descCgForNm((String)jCbAltCargo.getSelectedItem()));
        
        FuncionarioDAO fcDAO = new FuncionarioDAO();
        fcDAO.alterarFunc(fc, cg);
        
        JOptionPane.showMessageDialog(null, "Funcionário "+fc.getNome()+" alterado com sucesso!");
        listarFuncionarios();
        
        jTxtAltNome.setText("");
        jTxtAltNome.setEnabled(false);
        jTxtAltRg.setText("");
        jTxtAltRg.setEnabled(false);
        jFormTxtAltCpf.setText("");
        jFormTxtAltCpf.setEnabled(false);
        jTxtAltId.setText("");
        int i = 0;
        jCbAltCargo.setSelectedItem(jCbAltCargo.getItemAt(i));
        jCbAltCargo.setEnabled(false);
        jBtAlterar.setEnabled(false);
        jBtExcluir.setEnabled(false);
    }//GEN-LAST:event_jBtAlterarActionPerformed

    private void jTableFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFuncionariosMouseClicked
        jTxtAltId.setText((String) jTableFuncionarios.getModel().getValueAt(jTableFuncionarios.getSelectedRow(), 0));
        jTxtAltNome.setEnabled(true);
        jTxtAltNome.setText((String) jTableFuncionarios.getModel().getValueAt(jTableFuncionarios.getSelectedRow(), 1));
        jTxtAltRg.setEnabled(true);
        jTxtAltRg.setText((String) jTableFuncionarios.getModel().getValueAt(jTableFuncionarios.getSelectedRow(), 2));
        jFormTxtAltCpf.setEnabled(true);
        jFormTxtAltCpf.setText((String) jTableFuncionarios.getModel().getValueAt(jTableFuncionarios.getSelectedRow(), 3));
        jCbAltCargo.setEnabled(true);
        jBtAlterar.setEnabled(true);
        jBtExcluir.setEnabled(true);
    }//GEN-LAST:event_jTableFuncionariosMouseClicked

    private void jBtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtExcluirActionPerformed
        Funcionario fc = new Funcionario();
        fc.setId(Integer.parseInt(jTxtAltId.getText()));
        
        FuncionarioDAO fcDAO = new FuncionarioDAO();
        fcDAO.excluirFunc(fc);
        
        JOptionPane.showMessageDialog(null, "Funcionário "+fc.getNome()+" excluído com sucesso!");
        listarFuncionarios();
        
        jTxtAltNome.setText("");
        jTxtAltNome.setEnabled(false);
        jTxtAltRg.setText("");
        jTxtAltRg.setEnabled(false);
        jFormTxtAltCpf.setText("");
        jFormTxtAltCpf.setEnabled(false);
        jTxtAltId.setText("");
        int i = 0;
        jCbAltCargo.setSelectedItem(jCbAltCargo.getItemAt(i));
        jCbAltCargo.setEnabled(false);
        jBtAlterar.setEnabled(false);
        jBtExcluir.setEnabled(false);
    }//GEN-LAST:event_jBtExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLbCg;
    private javax.swing.JLabel JLbCg1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtAltCargo;
    private javax.swing.JButton jBtAlterar;
    private javax.swing.JButton jBtCadCargo;
    private javax.swing.JButton jBtCadastrar;
    private javax.swing.JPanel jBtCargos;
    private javax.swing.JButton jBtExcCargo;
    private javax.swing.JButton jBtExcluir;
    private javax.swing.JPanel jBtFuncionarios;
    private javax.swing.JComboBox<String> jCbAltCargo;
    private javax.swing.JComboBox<String> jCbCargo;
    private javax.swing.JFormattedTextField jFormTxtAltCpf;
    private javax.swing.JFormattedTextField jFormTxtCpf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLbCargos;
    private javax.swing.JLabel jLbCg2;
    private javax.swing.JLabel jLbCg3;
    private javax.swing.JLabel jLbCg4;
    private javax.swing.JLabel jLbCg5;
    private javax.swing.JLabel jLbCg6;
    private javax.swing.JLabel jLbCg7;
    private javax.swing.JLabel jLbCg8;
    private javax.swing.JLabel jLbExit;
    private javax.swing.JLabel jLbGFunc;
    private javax.swing.JLabel jLbGFunc1;
    private javax.swing.JLabel jLbGFunc6;
    private javax.swing.JLabel jLbIconCargos;
    private javax.swing.JLabel jLbIconFunc;
    private javax.swing.JPanel jPanelCargos;
    private javax.swing.JPanel jPanelFuncionarios;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JPanel jPanelTopBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableCargos;
    private javax.swing.JTable jTableFuncionarios;
    private javax.swing.JTextArea jTxtAltDescricao;
    private javax.swing.JTextField jTxtAltId;
    private javax.swing.JTextField jTxtAltNome;
    private javax.swing.JTextField jTxtAltRg;
    private javax.swing.JTextField jTxtAltSalario;
    private javax.swing.JTextField jTxtCargo;
    private javax.swing.JTextArea jTxtDescricao;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtRg;
    private javax.swing.JTextField jTxtSalario;
    private javax.swing.JTextField jTxtSigla;
    // End of variables declaration//GEN-END:variables
}
