/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;

/**
 *
 * @author izael
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form JFrameInicial
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTopBar = new javax.swing.JPanel();
        jLbExit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelLeft = new javax.swing.JPanel();
        jBtFuncionarios = new javax.swing.JPanel();
        jLbGFunc = new javax.swing.JLabel();
        jLbIconFunc = new javax.swing.JLabel();
        jBtCargos = new javax.swing.JPanel();
        jLbIconCargos = new javax.swing.JLabel();
        jLbCargos = new javax.swing.JLabel();
        jPanelRight = new javax.swing.JPanel();
        jPanelFuncionarios = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTopBar.setBackground(new java.awt.Color(102, 0, 0));
        jPanelTopBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelTopBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbExit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLbExit.setForeground(new java.awt.Color(255, 255, 255));
        jLbExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbExit.setText("X");
        jLbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbExitMouseExited(evt);
            }
        });
        jPanelTopBar.add(jLbExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 30, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gerenciamento de Funcionários");
        jPanelTopBar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        getContentPane().add(jPanelTopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 30));

        jPanelLeft.setBackground(new java.awt.Color(51, 51, 51));
        jPanelLeft.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelLeft.setForeground(new java.awt.Color(51, 51, 51));
        jPanelLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtFuncionarios.setBackground(new java.awt.Color(51, 51, 51));
        jBtFuncionarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbGFunc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbGFunc.setForeground(new java.awt.Color(255, 255, 255));
        jLbGFunc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbGFunc.setText("         Funcionários");
        jLbGFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbGFuncMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbGFuncMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbGFuncMouseExited(evt);
            }
        });
        jBtFuncionarios.add(jLbGFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 60));

        jLbIconFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/funcionario.png"))); // NOI18N
        jBtFuncionarios.add(jLbIconFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 60));

        jPanelLeft.add(jBtFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 180, 60));

        jBtCargos.setBackground(new java.awt.Color(51, 51, 51));
        jBtCargos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbIconCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cargo.png"))); // NOI18N
        jBtCargos.add(jLbIconCargos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 60));

        jLbCargos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbCargos.setForeground(new java.awt.Color(255, 255, 255));
        jLbCargos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbCargos.setText("      Cargos");
        jLbCargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbCargosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbCargosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbCargosMouseExited(evt);
            }
        });
        jBtCargos.add(jLbCargos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 60));

        jPanelLeft.add(jBtCargos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 180, 60));

        getContentPane().add(jPanelLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 500));

        jPanelRight.setBackground(new java.awt.Color(204, 51, 0));
        jPanelRight.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelRight.setLayout(new java.awt.CardLayout());

        jPanelFuncionarios.setBackground(new java.awt.Color(204, 51, 0));

        javax.swing.GroupLayout jPanelFuncionariosLayout = new javax.swing.GroupLayout(jPanelFuncionarios);
        jPanelFuncionarios.setLayout(jPanelFuncionariosLayout);
        jPanelFuncionariosLayout.setHorizontalGroup(
            jPanelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        jPanelFuncionariosLayout.setVerticalGroup(
            jPanelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        jPanelRight.add(jPanelFuncionarios, "TelaFuncionario");

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        jPanelRight.add(jPanel1, "TelaCargos");

        getContentPane().add(jPanelRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 690, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLbCargosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbCargosMouseEntered
        this.setCursor(Cursor.HAND_CURSOR);
        jBtCargos.setBackground(new Color(83,83,83));
    }//GEN-LAST:event_jLbCargosMouseEntered

    private void jLbCargosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbCargosMouseExited
        this.setCursor(Cursor.DEFAULT_CURSOR);
        jBtCargos.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jLbCargosMouseExited

    private void jLbCargosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbCargosMouseClicked
        CardLayout cl = (CardLayout) jPanelRight.getLayout();
        cl.show(jPanelRight, "TelaCargos");
        jPanelRight.setBackground(new Color(255,204,0));
    }//GEN-LAST:event_jLbCargosMouseClicked

    private void jLbGFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFuncMouseClicked
        CardLayout cl = (CardLayout) jPanelRight.getLayout();
        cl.show(jPanelRight, "TelaFuncionario");
        jPanelRight.setBackground(new Color(204,51,0));
    }//GEN-LAST:event_jLbGFuncMouseClicked

    private void jLbGFuncMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFuncMouseEntered
        this.setCursor(Cursor.HAND_CURSOR);
        jBtFuncionarios.setBackground(new Color(83,83,83));
    }//GEN-LAST:event_jLbGFuncMouseEntered

    private void jLbGFuncMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFuncMouseExited
        this.setCursor(Cursor.DEFAULT_CURSOR);
        jBtFuncionarios.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jLbGFuncMouseExited

    private void jLbExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbExitMouseEntered
        this.setCursor(Cursor.HAND_CURSOR);
        jLbExit.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_jLbExitMouseEntered

    private void jLbExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbExitMouseExited
        this.setCursor(Cursor.DEFAULT_CURSOR);
        jLbExit.setForeground(new Color(240,240,240));
    }//GEN-LAST:event_jLbExitMouseExited

    private void jLbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLbExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBtCargos;
    private javax.swing.JPanel jBtFuncionarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbCargos;
    private javax.swing.JLabel jLbExit;
    private javax.swing.JLabel jLbGFunc;
    private javax.swing.JLabel jLbIconCargos;
    private javax.swing.JLabel jLbIconFunc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFuncionarios;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JPanel jPanelTopBar;
    // End of variables declaration//GEN-END:variables
}
