/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;

/**
 *
 * @author izael
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form JFrameInicial
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelTopBar = new javax.swing.JPanel();
        jLbExit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelLeft = new javax.swing.JPanel();
        jBtFuncionarios = new javax.swing.JPanel();
        jLbIconFunc = new javax.swing.JLabel();
        jLbGFunc = new javax.swing.JLabel();
        jBtCargos = new javax.swing.JPanel();
        jLbIconCargos = new javax.swing.JLabel();
        jLbCargos = new javax.swing.JLabel();
        jPanelRight = new javax.swing.JPanel();
        jPanelFuncionarios = new javax.swing.JPanel();
        jLbGFunc1 = new javax.swing.JLabel();
        jLbGFunc2 = new javax.swing.JLabel();
        jLbGFunc3 = new javax.swing.JLabel();
        jLbGFunc4 = new javax.swing.JLabel();
        jLbGFunc5 = new javax.swing.JLabel();
        jTxtRg = new javax.swing.JTextField();
        jTxtNome = new javax.swing.JTextField();
        jFormTxtCpf = new javax.swing.JFormattedTextField();
        jCbCargo = new javax.swing.JComboBox<>();
        jLbGFunc6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLbGFunc7 = new javax.swing.JLabel();
        jRbCpf = new javax.swing.JRadioButton();
        jRbNome = new javax.swing.JRadioButton();
        jTxtPesquisa = new javax.swing.JTextField();
        jBtPesquisa = new javax.swing.JButton();
        jLbGFunc8 = new javax.swing.JLabel();
        jLbGFunc9 = new javax.swing.JLabel();
        jLbGFunc10 = new javax.swing.JLabel();
        jLbGFunc11 = new javax.swing.JLabel();
        jLbGFunc12 = new javax.swing.JLabel();
        jTxtAltRg = new javax.swing.JTextField();
        jTxtAltId = new javax.swing.JTextField();
        jTxtAltNome = new javax.swing.JTextField();
        jFormTxtAltCpf = new javax.swing.JFormattedTextField();
        jCbAltCargo = new javax.swing.JComboBox<>();
        jBtCadastrar = new javax.swing.JButton();
        jBtExcluir = new javax.swing.JButton();
        jBtAlterar = new javax.swing.JButton();
        jPanelCargos = new javax.swing.JPanel();
        JLbCg = new javax.swing.JLabel();
        jLbCg2 = new javax.swing.JLabel();
        jLbCg3 = new javax.swing.JLabel();
        jLbCg4 = new javax.swing.JLabel();
        jLbCg5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtAltDescricao = new javax.swing.JTextArea();
        jTtxSigla = new javax.swing.JTextField();
        jTxtSalario = new javax.swing.JTextField();
        jLbCg6 = new javax.swing.JLabel();
        jTxtCargo1 = new javax.swing.JTextField();
        JLbCg1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLbCg7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTxtDescricao = new javax.swing.JTextArea();
        jLbCg8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtAltSalario = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTopBar.setBackground(new java.awt.Color(102, 0, 0));
        jPanelTopBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelTopBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbExit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLbExit.setForeground(new java.awt.Color(255, 255, 255));
        jLbExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbExit.setText("X");
        jLbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbExitMouseExited(evt);
            }
        });
        jPanelTopBar.add(jLbExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 30, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gerenciamento de Funcionários");
        jPanelTopBar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        getContentPane().add(jPanelTopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 30));

        jPanelLeft.setBackground(new java.awt.Color(51, 51, 51));
        jPanelLeft.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelLeft.setForeground(new java.awt.Color(51, 51, 51));
        jPanelLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtFuncionarios.setBackground(new java.awt.Color(51, 51, 51));
        jBtFuncionarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbIconFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/funcionario.png"))); // NOI18N
        jBtFuncionarios.add(jLbIconFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 60));

        jLbGFunc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbGFunc.setForeground(new java.awt.Color(255, 255, 255));
        jLbGFunc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbGFunc.setText("         Funcionários");
        jLbGFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbGFuncMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbGFuncMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbGFuncMouseExited(evt);
            }
        });
        jBtFuncionarios.add(jLbGFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 60));

        jPanelLeft.add(jBtFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 180, 60));

        jBtCargos.setBackground(new java.awt.Color(51, 51, 51));
        jBtCargos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbIconCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cargo.png"))); // NOI18N
        jBtCargos.add(jLbIconCargos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 60));

        jLbCargos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbCargos.setForeground(new java.awt.Color(255, 255, 255));
        jLbCargos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbCargos.setText("      Cargos");
        jLbCargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbCargosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbCargosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbCargosMouseExited(evt);
            }
        });
        jBtCargos.add(jLbCargos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 60));

        jPanelLeft.add(jBtCargos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 180, 60));

        getContentPane().add(jPanelLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 500));

        jPanelRight.setBackground(new java.awt.Color(230, 230, 230));
        jPanelRight.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelRight.setLayout(new java.awt.CardLayout());

        jPanelFuncionarios.setBackground(new java.awt.Color(230, 230, 230));
        jPanelFuncionarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbGFunc1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLbGFunc1.setForeground(new java.awt.Color(51, 51, 51));
        jLbGFunc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbGFunc1.setText("Editar/Excluir Funcionário:");
        jLbGFunc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbGFunc1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbGFunc1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbGFunc1MouseExited(evt);
            }
        });
        jPanelFuncionarios.add(jLbGFunc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 280, 30));

        jLbGFunc2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbGFunc2.setForeground(new java.awt.Color(51, 51, 51));
        jLbGFunc2.setText("ID:");
        jLbGFunc2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbGFunc2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbGFunc2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbGFunc2MouseExited(evt);
            }
        });
        jPanelFuncionarios.add(jLbGFunc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 70, 20));

        jLbGFunc3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbGFunc3.setForeground(new java.awt.Color(51, 51, 51));
        jLbGFunc3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbGFunc3.setText("Pesquisar:");
        jLbGFunc3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbGFunc3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbGFunc3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbGFunc3MouseExited(evt);
            }
        });
        jPanelFuncionarios.add(jLbGFunc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 90, 20));

        jLbGFunc4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbGFunc4.setForeground(new java.awt.Color(51, 51, 51));
        jLbGFunc4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbGFunc4.setText("CPF:");
        jLbGFunc4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbGFunc4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbGFunc4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbGFunc4MouseExited(evt);
            }
        });
        jPanelFuncionarios.add(jLbGFunc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 70, 20));

        jLbGFunc5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbGFunc5.setForeground(new java.awt.Color(51, 51, 51));
        jLbGFunc5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbGFunc5.setText("Cargo:");
        jLbGFunc5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbGFunc5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbGFunc5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbGFunc5MouseExited(evt);
            }
        });
        jPanelFuncionarios.add(jLbGFunc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 70, 20));

        jTxtRg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanelFuncionarios.add(jTxtRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 210, -1));

        jTxtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanelFuncionarios.add(jTxtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 210, -1));

        try {
            jFormTxtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormTxtCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanelFuncionarios.add(jFormTxtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 210, -1));

        jCbCargo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelFuncionarios.add(jCbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 210, -1));

        jLbGFunc6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLbGFunc6.setForeground(new java.awt.Color(51, 51, 51));
        jLbGFunc6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbGFunc6.setText("Cadastro de Funcionário");
        jLbGFunc6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbGFunc6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbGFunc6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbGFunc6MouseExited(evt);
            }
        });
        jPanelFuncionarios.add(jLbGFunc6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 250, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanelFuncionarios.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 620, 140));

        jLbGFunc7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbGFunc7.setForeground(new java.awt.Color(51, 51, 51));
        jLbGFunc7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbGFunc7.setText("RG:");
        jLbGFunc7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbGFunc7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbGFunc7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbGFunc7MouseExited(evt);
            }
        });
        jPanelFuncionarios.add(jLbGFunc7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 50, 20));

        jRbCpf.setBackground(new java.awt.Color(230, 230, 230));
        buttonGroup1.add(jRbCpf);
        jRbCpf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRbCpf.setText("CPF");
        jPanelFuncionarios.add(jRbCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        jRbNome.setBackground(new java.awt.Color(230, 230, 230));
        buttonGroup1.add(jRbNome);
        jRbNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRbNome.setText("Nome");
        jPanelFuncionarios.add(jRbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jTxtPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTxtPesquisa.setText("jTextField1");
        jPanelFuncionarios.add(jTxtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 150, -1));

        jBtPesquisa.setBackground(new java.awt.Color(153, 0, 0));
        jBtPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBtPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        jBtPesquisa.setText("Pesquisar");
        jPanelFuncionarios.add(jBtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        jLbGFunc8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbGFunc8.setForeground(new java.awt.Color(51, 51, 51));
        jLbGFunc8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbGFunc8.setText("Nome:");
        jLbGFunc8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbGFunc8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbGFunc8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbGFunc8MouseExited(evt);
            }
        });
        jPanelFuncionarios.add(jLbGFunc8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 70, 20));

        jLbGFunc9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbGFunc9.setForeground(new java.awt.Color(51, 51, 51));
        jLbGFunc9.setText("Nome:");
        jLbGFunc9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbGFunc9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbGFunc9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbGFunc9MouseExited(evt);
            }
        });
        jPanelFuncionarios.add(jLbGFunc9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 70, 20));

        jLbGFunc10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbGFunc10.setForeground(new java.awt.Color(51, 51, 51));
        jLbGFunc10.setText("RG:");
        jLbGFunc10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbGFunc10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbGFunc10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbGFunc10MouseExited(evt);
            }
        });
        jPanelFuncionarios.add(jLbGFunc10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 70, 20));

        jLbGFunc11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbGFunc11.setForeground(new java.awt.Color(51, 51, 51));
        jLbGFunc11.setText("CPF:");
        jLbGFunc11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbGFunc11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbGFunc11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbGFunc11MouseExited(evt);
            }
        });
        jPanelFuncionarios.add(jLbGFunc11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 70, 20));

        jLbGFunc12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbGFunc12.setForeground(new java.awt.Color(51, 51, 51));
        jLbGFunc12.setText("Cargo:");
        jLbGFunc12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbGFunc12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbGFunc12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbGFunc12MouseExited(evt);
            }
        });
        jPanelFuncionarios.add(jLbGFunc12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 70, 20));

        jTxtAltRg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtAltRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAltRgActionPerformed(evt);
            }
        });
        jPanelFuncionarios.add(jTxtAltRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 210, -1));

        jTxtAltId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanelFuncionarios.add(jTxtAltId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 100, -1));

        jTxtAltNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanelFuncionarios.add(jTxtAltNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 210, -1));

        jFormTxtAltCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanelFuncionarios.add(jFormTxtAltCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 200, -1));

        jCbAltCargo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCbAltCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelFuncionarios.add(jCbAltCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 200, -1));

        jBtCadastrar.setBackground(new java.awt.Color(153, 0, 0));
        jBtCadastrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jBtCadastrar.setText("Cadastrar");
        jPanelFuncionarios.add(jBtCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 110, 30));

        jBtExcluir.setBackground(new java.awt.Color(153, 0, 0));
        jBtExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jBtExcluir.setText("Excluir");
        jPanelFuncionarios.add(jBtExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 90, -1));

        jBtAlterar.setBackground(new java.awt.Color(153, 0, 0));
        jBtAlterar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jBtAlterar.setText("Alterar");
        jPanelFuncionarios.add(jBtAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 90, 30));

        jPanelRight.add(jPanelFuncionarios, "TelaFuncionario");

        jPanelCargos.setBackground(new java.awt.Color(230, 230, 230));
        jPanelCargos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLbCg.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        JLbCg.setText("Editar/Excluir Cargo");
        jPanelCargos.add(JLbCg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLbCg2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLbCg2.setText("R$");
        jPanelCargos.add(jLbCg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLbCg3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbCg3.setText("Cargo:");
        jPanelCargos.add(jLbCg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLbCg4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbCg4.setText("Salário:");
        jPanelCargos.add(jLbCg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLbCg5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbCg5.setText("Sigla:");
        jPanelCargos.add(jLbCg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jTxtAltDescricao.setColumns(20);
        jTxtAltDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtAltDescricao.setRows(5);
        jScrollPane2.setViewportView(jTxtAltDescricao);

        jPanelCargos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 260, 70));

        jTtxSigla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanelCargos.add(jTtxSigla, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 170, -1));

        jTxtSalario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanelCargos.add(jTxtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 140, -1));

        jLbCg6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbCg6.setText("Salário:");
        jPanelCargos.add(jLbCg6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jTxtCargo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanelCargos.add(jTxtCargo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 170, -1));

        JLbCg1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        JLbCg1.setText("Cadastro de Cargo");
        jPanelCargos.add(JLbCg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Excluir");
        jPanelCargos.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        jLabel2.setText("*Só é possível alterar a descrição e o salário, caso contrário, apenas exclusão.");
        jPanelCargos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanelCargos.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 620, 140));

        jLbCg7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbCg7.setText("Descrição:");
        jPanelCargos.add(jLbCg7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        jTxtDescricao.setColumns(20);
        jTxtDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtDescricao.setRows(5);
        jScrollPane4.setViewportView(jTxtDescricao);

        jPanelCargos.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 260, 70));

        jLbCg8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLbCg8.setText("Descrição:");
        jPanelCargos.add(jLbCg8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("R$");
        jPanelCargos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        jTxtAltSalario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanelCargos.add(jTxtAltSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 170, -1));

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cadastrar");
        jPanelCargos.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Alterar");
        jPanelCargos.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jPanelRight.add(jPanelCargos, "TelaCargos");

        getContentPane().add(jPanelRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 690, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLbCargosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbCargosMouseEntered
        this.setCursor(Cursor.HAND_CURSOR);
        jBtCargos.setBackground(new Color(83,83,83));
    }//GEN-LAST:event_jLbCargosMouseEntered

    private void jLbCargosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbCargosMouseExited
        this.setCursor(Cursor.DEFAULT_CURSOR);
        jBtCargos.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jLbCargosMouseExited

    private void jLbCargosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbCargosMouseClicked
        CardLayout cl = (CardLayout) jPanelRight.getLayout();
        cl.show(jPanelRight, "TelaCargos");
    }//GEN-LAST:event_jLbCargosMouseClicked

    private void jLbGFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFuncMouseClicked
        CardLayout cl = (CardLayout) jPanelRight.getLayout();
        cl.show(jPanelRight, "TelaFuncionario");
    }//GEN-LAST:event_jLbGFuncMouseClicked

    private void jLbGFuncMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFuncMouseEntered
        this.setCursor(Cursor.HAND_CURSOR);
        jBtFuncionarios.setBackground(new Color(83,83,83));
    }//GEN-LAST:event_jLbGFuncMouseEntered

    private void jLbGFuncMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFuncMouseExited
        this.setCursor(Cursor.DEFAULT_CURSOR);
        jBtFuncionarios.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jLbGFuncMouseExited

    private void jLbExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbExitMouseEntered
        this.setCursor(Cursor.HAND_CURSOR);
        jLbExit.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_jLbExitMouseEntered

    private void jLbExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbExitMouseExited
        this.setCursor(Cursor.DEFAULT_CURSOR);
        jLbExit.setForeground(new Color(240,240,240));
    }//GEN-LAST:event_jLbExitMouseExited

    private void jLbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLbExitMouseClicked

    private void jLbGFunc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc1MouseClicked

    private void jLbGFunc1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc1MouseEntered

    private void jLbGFunc1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc1MouseExited

    private void jLbGFunc2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc2MouseClicked

    private void jLbGFunc2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc2MouseEntered

    private void jLbGFunc2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc2MouseExited

    private void jLbGFunc3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc3MouseClicked

    private void jLbGFunc3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc3MouseEntered

    private void jLbGFunc3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc3MouseExited

    private void jLbGFunc4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc4MouseClicked

    private void jLbGFunc4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc4MouseEntered

    private void jLbGFunc4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc4MouseExited

    private void jLbGFunc5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc5MouseClicked

    private void jLbGFunc5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc5MouseEntered

    private void jLbGFunc5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc5MouseExited

    private void jLbGFunc6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc6MouseClicked

    private void jLbGFunc6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc6MouseEntered

    private void jLbGFunc6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc6MouseExited

    private void jLbGFunc7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc7MouseClicked

    private void jLbGFunc7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc7MouseEntered

    private void jLbGFunc7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc7MouseExited

    private void jLbGFunc8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc8MouseClicked

    private void jLbGFunc8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc8MouseEntered

    private void jLbGFunc8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc8MouseExited

    private void jLbGFunc9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc9MouseClicked

    private void jLbGFunc9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc9MouseEntered

    private void jLbGFunc9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc9MouseExited

    private void jLbGFunc10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc10MouseClicked

    private void jLbGFunc10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc10MouseEntered

    private void jLbGFunc10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc10MouseExited

    private void jLbGFunc11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc11MouseClicked

    private void jLbGFunc11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc11MouseEntered

    private void jLbGFunc11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc11MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc11MouseExited

    private void jLbGFunc12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc12MouseClicked

    private void jLbGFunc12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc12MouseEntered

    private void jLbGFunc12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbGFunc12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbGFunc12MouseExited

    private void jTxtAltRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAltRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAltRgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLbCg;
    private javax.swing.JLabel JLbCg1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtAlterar;
    private javax.swing.JButton jBtCadastrar;
    private javax.swing.JPanel jBtCargos;
    private javax.swing.JButton jBtExcluir;
    private javax.swing.JPanel jBtFuncionarios;
    private javax.swing.JButton jBtPesquisa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jCbAltCargo;
    private javax.swing.JComboBox<String> jCbCargo;
    private javax.swing.JFormattedTextField jFormTxtAltCpf;
    private javax.swing.JFormattedTextField jFormTxtCpf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLbCargos;
    private javax.swing.JLabel jLbCg2;
    private javax.swing.JLabel jLbCg3;
    private javax.swing.JLabel jLbCg4;
    private javax.swing.JLabel jLbCg5;
    private javax.swing.JLabel jLbCg6;
    private javax.swing.JLabel jLbCg7;
    private javax.swing.JLabel jLbCg8;
    private javax.swing.JLabel jLbExit;
    private javax.swing.JLabel jLbGFunc;
    private javax.swing.JLabel jLbGFunc1;
    private javax.swing.JLabel jLbGFunc10;
    private javax.swing.JLabel jLbGFunc11;
    private javax.swing.JLabel jLbGFunc12;
    private javax.swing.JLabel jLbGFunc2;
    private javax.swing.JLabel jLbGFunc3;
    private javax.swing.JLabel jLbGFunc4;
    private javax.swing.JLabel jLbGFunc5;
    private javax.swing.JLabel jLbGFunc6;
    private javax.swing.JLabel jLbGFunc7;
    private javax.swing.JLabel jLbGFunc8;
    private javax.swing.JLabel jLbGFunc9;
    private javax.swing.JLabel jLbIconCargos;
    private javax.swing.JLabel jLbIconFunc;
    private javax.swing.JPanel jPanelCargos;
    private javax.swing.JPanel jPanelFuncionarios;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JPanel jPanelTopBar;
    private javax.swing.JRadioButton jRbCpf;
    private javax.swing.JRadioButton jRbNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTtxSigla;
    private javax.swing.JTextArea jTxtAltDescricao;
    private javax.swing.JTextField jTxtAltId;
    private javax.swing.JTextField jTxtAltNome;
    private javax.swing.JTextField jTxtAltRg;
    private javax.swing.JTextField jTxtAltSalario;
    private javax.swing.JTextField jTxtCargo1;
    private javax.swing.JTextArea jTxtDescricao;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtPesquisa;
    private javax.swing.JTextField jTxtRg;
    private javax.swing.JTextField jTxtSalario;
    // End of variables declaration//GEN-END:variables
}
